on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v4.1.5
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --clean client/sendLog.py
    - run: pyinstaller --onefile --clean client/update.py
    - uses: vimtor/action-zip@v1.2
      with:
        files: "dist/*"
        dest: bin-${{ matrix.os }}.zip
    - uses: softprops/action-gh-release@v2.0.5
      with:
        draft: true
        files: "dist/*"
        token: ${{ secrets.MAKE_RELEASE_TOKEN }}
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: bin-${{ matrix.os }}.zip
        path: dist/*
